# Python project, check against all supported things.
language: python

matrix:
  include:
    - os: linux
      python: 3.7
      dist: xenial
      sudo: required

# disable submodules from git
git:
  submodules: false
# commands to install dependencies
install:
  - 'if [ -x "$(command -v apt-get)" ]; then sudo apt-get install optipng jpegoptim; fi'
  - python3.7 -m pip install pipenv
  - python3.7 -m pipenv install --dev
# commands to run tests
script:
  - python3.7 -m pipenv run python update.py --update-docs --check-pages
  - python3.7 -m pipenv run python update.py --build-site
