name: Nuitka website tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Website Build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt-get install python3.9
          python3.9 -m pip install -U pipenv
          python3.9 -m pipenv install

      - name: Build site
        run: |
          python3.9 -m pipenv run python update.py --update-docs
          python3.9 -m pipenv run python update.py --build-site
